-- Update team names to use common short names (without FC/AFC suffixes)

UPDATE teams SET name = 'Arsenal' WHERE name = 'Arsenal FC';
UPDATE teams SET name = 'Aston Villa' WHERE name = 'Aston Villa FC';
UPDATE teams SET name = 'Chelsea' WHERE name = 'Chelsea FC';
UPDATE teams SET name = 'Everton' WHERE name = 'Everton FC';
UPDATE teams SET name = 'Liverpool' WHERE name = 'Liverpool FC';
UPDATE teams SET name = 'Manchester City' WHERE name = 'Manchester City FC';
UPDATE teams SET name = 'Manchester United' WHERE name = 'Manchester United FC';
UPDATE teams SET name = 'Tottenham' WHERE name = 'Tottenham Hotspur FC';
UPDATE teams SET name = 'Fulham' WHERE name = 'Fulham FC';
UPDATE teams SET name = 'Leeds United' WHERE name = 'Leeds United FC';
UPDATE teams SET name = 'Newcastle United' WHERE name = 'Newcastle United FC';
UPDATE teams SET name = 'Nottingham Forest' WHERE name = 'Nottingham Forest FC';
UPDATE teams SET name = 'Sheffield United' WHERE name = 'Sheffield United FC';
UPDATE teams SET name = 'Sheffield Wednesday' WHERE name = 'Sheffield Wednesday FC';
UPDATE teams SET name = 'Wolverhampton' WHERE name = 'Wolverhampton Wanderers FC';
UPDATE teams SET name = 'West Ham' WHERE name = 'West Ham United FC';
UPDATE teams SET name = 'Blackburn' WHERE name = 'Blackburn Rovers FC';
UPDATE teams SET name = 'Bolton' WHERE name = 'Bolton Wanderers FC';
UPDATE teams SET name = 'Sunderland' WHERE name = 'Sunderland AFC';
UPDATE teams SET name = 'Burnley' WHERE name = 'Burnley FC';
UPDATE teams SET name = 'Leicester City' WHERE name = 'Leicester City FC';
UPDATE teams SET name = 'Southampton' WHERE name = 'Southampton FC';
UPDATE teams SET name = 'Crystal Palace' WHERE name = 'Crystal Palace FC';
UPDATE teams SET name = 'West Brom' WHERE name = 'West Bromwich Albion FC';
UPDATE teams SET name = 'Norwich City' WHERE name = 'Norwich City FC';
UPDATE teams SET name = 'QPR' WHERE name = 'Queens Park Rangers FC';
UPDATE teams SET name = 'Coventry City' WHERE name = 'Coventry City FC';
UPDATE teams SET name = 'Oldham' WHERE name = 'Oldham Athletic AFC';
UPDATE teams SET name = 'Ipswich' WHERE name = 'Ipswich Town FC';
UPDATE teams SET name = 'Wimbledon' WHERE name = 'Wimbledon FC';
UPDATE teams SET name = 'Swindon' WHERE name = 'Swindon Town FC';
UPDATE teams SET name = 'Middlesbrough' WHERE name = 'Middlesbrough FC';
UPDATE teams SET name = 'Derby County' WHERE name = 'Derby County FC';
UPDATE teams SET name = 'Barnsley' WHERE name = 'Barnsley FC';
UPDATE teams SET name = 'Birmingham City' WHERE name = 'Birmingham City FC';
UPDATE teams SET name = 'Portsmouth' WHERE name = 'Portsmouth FC';
UPDATE teams SET name = 'Watford' WHERE name = 'Watford FC';
UPDATE teams SET name = 'Wigan' WHERE name = 'Wigan Athletic FC';
UPDATE teams SET name = 'Reading' WHERE name = 'Reading FC';
UPDATE teams SET name = 'Stoke City' WHERE name = 'Stoke City FC';
UPDATE teams SET name = 'Swansea' WHERE name = 'Swansea City AFC';
UPDATE teams SET name = 'Hull City' WHERE name = 'Hull City AFC';
UPDATE teams SET name = 'Cardiff City' WHERE name = 'Cardiff City FC';
UPDATE teams SET name = 'Bournemouth' WHERE name = 'AFC Bournemouth';
UPDATE teams SET name = 'Brighton' WHERE name = 'Brighton & Hove Albion FC';
UPDATE teams SET name = 'Brentford' WHERE name = 'Brentford FC';
UPDATE teams SET name = 'Huddersfield' WHERE name = 'Huddersfield Town AFC';
UPDATE teams SET name = 'Luton' WHERE name = 'Luton Town FC';
UPDATE teams SET name = 'Charlton' WHERE name = 'Charlton Athletic FC';
UPDATE teams SET name = 'Bradford City' WHERE name = 'Bradford City AFC';